# Generated by Django 4.2.5 on 2023-09-21 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alert',
            old_name='amount',
            new_name='percentage_change',
        ),
        migrations.AddField(
            model_name='alert',
            name='high_amount',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='low_amount',
            field=models.FloatField(null=True),
        ),
    ]
